### ISSUE TITLE
Not working on up-to-date 64 bit Raspberry Pi image

### ISSUE THREAD

**Issue by capiman** [freeconf/lang#2]
```
$ fc-lang-install -v
downloading https://github.com/freeconf/lang/releases/download/v0.1.0-alpha/fc-lang-0.1.0-linux-aarch64 to /home/xxx/.freeconf/bin/fc-lang-0.1.0-linux-aarch64
Traceback (most recent call last):
  File "/home/xxx/.local/bin/fc-lang-install", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/xxx/.local/lib/python3.12/site-packages/freeconf/install.py", line 60, in run
    raise Exception("{resp._status_code} error downloading {url}")
Exception: {resp._status_code} error downloading {url}
$
```

Linux aarch64 seems not be in the list of released versions:
https://github.com/freeconf/lang/releases/tag/v0.1.0-alpha

**Comment by capiman** [comment]
Same seems to be the case for a new Notebook with a Snapdragon, 
which uses (not tried, but assuming)

windows-arm64

or

linux-arm64

Can I somehow take the released sources and compile myself?

**Comment by dhubler** [comment]
yes you can, source is here
  https://github.com/freeconf/lang

We can add linux arm to set of binaries going forward as well.

**Comment by dhubler** [comment]
Sorry, you seem to know the project already.  Project contains the source
for both Go and  Python

You'll see the platforms here
  https://github.com/freeconf/lang/blob/main/Makefile

If you add your os-arch you should get a binary.  You can safely compile
this on any OS for any other OS.
